// data_worldCapitals.js - embedded world capitals grouped by continent
const WORLD_CAPITALS = [
  { continent: "Africa", country: "Morocco", capital: "Rabat" },
  { continent: "Africa", country: "Algeria", capital: "Algiers" },
  { continent: "Africa", country: "Tunisia", capital: "Tunis" },
  { continent: "Africa", country: "Libya", capital: "Tripoli" },
  { continent: "Africa", country: "Egypt", capital: "Cairo" },
  { continent: "Africa", country: "Mauritania", capital: "Nouakchott" },
  { continent: "Africa", country: "Mali", capital: "Bamako" },
  { continent: "Africa", country: "Niger", capital: "Niamey" },
  { continent: "Africa", country: "Chad", capital: "N'Djamena" },
  { continent: "Africa", country: "Sudan", capital: "Khartoum" },
  { continent: "Africa", country: "Eritrea", capital: "Asmara" },
  { continent: "Africa", country: "Djibouti", capital: "Djibouti|Djibouti City" },
  { continent: "Africa", country: "Cabo Verde", capital: "Praia" },
  { continent: "Africa", country: "Gambia", capital: "Banjul" },
  { continent: "Africa", country: "Senegal", capital: "Dakar" },
  { continent: "Africa", country: "Guinea-Bissau", capital: "Bissau" },
  { continent: "Africa", country: "Guinea", capital: "Conakry" },
  { continent: "Africa", country: "Sierra Leone", capital: "Freetown" },
  { continent: "Africa", country: "Liberia", capital: "Monrovia" },
  { continent: "Africa", country: "Cote d'Ivoire", capital: "Yamoussoukro" },
  { continent: "Africa", country: "Burkina Faso", capital: "Ouagadougou" },
  { continent: "Africa", country: "Ghana", capital: "Accra" },
  { continent: "Africa", country: "Togo", capital: "Lome" },
  { continent: "Africa", country: "Benin", capital: "Porto-Novo" },
  { continent: "Africa", country: "Nigeria", capital: "Abuja" },
  { continent: "Africa", country: "Cameroon", capital: "Yaounde" },
  { continent: "Africa", country: "Central African Republic", capital: "Bangui" },
  { continent: "Africa", country: "South Sudan", capital: "Juba" },
  { continent: "Africa", country: "Ethiopia", capital: "Addis Ababa" },
  { continent: "Africa", country: "Somalia", capital: "Mogadishu" },
  { continent: "Africa", country: "Sao Tome and Principe", capital: "Sao Tome" },
  { continent: "Africa", country: "Equatorial Guinea", capital: "Malabo" },
  { continent: "Africa", country: "Gabon", capital: "Libreville" },
  { continent: "Africa", country: "Republic of the Congo", capital: "Brazzaville" },
  { continent: "Africa", country: "Democratic Republic of the Congo", capital: "Kinshasa" },
  { continent: "Africa", country: "Rwanda", capital: "Kigali" },
  { continent: "Africa", country: "Uganda", capital: "Kampala" },
  { continent: "Africa", country: "Kenya", capital: "Nairobi" },
  { continent: "Africa", country: "Burundi", capital: "Gitega" },
  { continent: "Africa", country: "Tanzania", capital: "Dodoma" },
  { continent: "Africa", country: "Seychelles", capital: "Victoria" },
  { continent: "Africa", country: "Angola", capital: "Luanda" },
  { continent: "Africa", country: "Zambia", capital: "Lusaka" },
  { continent: "Africa", country: "Malawi", capital: "Lilongwe" },
  { continent: "Africa", country: "Comoros", capital: "Moroni" },
  { continent: "Africa", country: "Namibia", capital: "Windhoek" },
  { continent: "Africa", country: "Botswana", capital: "Gaborone" },
  { continent: "Africa", country: "Zimbabwe", capital: "Harare" },
  { continent: "Africa", country: "Mozambique", capital: "Maputo" },
  { continent: "Africa", country: "Madagascar", capital: "Antananarivo" },
  { continent: "Africa", country: "Mauritius", capital: "Port Louis" },
  { continent: "Africa", country: "South Africa", capital: "Pretoria|Cape Town|Bloemfontein" },
  { continent: "Africa", country: "Lesotho", capital: "Maseru" },
  { continent: "Africa", country: "Eswatini", capital: "Mbabane|Lobamba" },
  { continent: "Asia", country: "Turkey", capital: "Ankara" },
  { continent: "Asia", country: "Cyprus", capital: "Nicosia" },
  { continent: "Asia", country: "Lebanon", capital: "Beirut" },
  { continent: "Asia", country: "Israel", capital: "Jerusalem" },
  { continent: "Asia", country: "Palestine", capital: "East Jerusalem" },
  { continent: "Asia", country: "Syria", capital: "Damascus" },
  { continent: "Asia", country: "Jordan", capital: "Amman" },
  { continent: "Asia", country: "Georgia", capital: "Tbilisi" },
  { continent: "Asia", country: "Armenia", capital: "Yerevan" },
  { continent: "Asia", country: "Azerbaijan", capital: "Baku" },
  { continent: "Asia", country: "Iraq", capital: "Baghdad" },
  { continent: "Asia", country: "Kuwait", capital: "Kuwait City" },
  { continent: "Asia", country: "Saudi Arabia", capital: "Riyadh" },
  { continent: "Asia", country: "Bahrain", capital: "Manama" },
  { continent: "Asia", country: "Qatar", capital: "Doha" },
  { continent: "Asia", country: "United Arab Emirates", capital: "Abu Dhabi" },
  { continent: "Asia", country: "Yemen", capital: "Sana'a" },
  { continent: "Asia", country: "Oman", capital: "Muscat" },
  { continent: "Asia", country: "Iran", capital: "Tehran" },
  { continent: "Asia", country: "Kazakhstan", capital: "Nur-Sultan" },
  { continent: "Asia", country: "Uzbekistan", capital: "Tashkent" },
  { continent: "Asia", country: "Turkmenistan", capital: "Ashgabat" },
  { continent: "Asia", country: "Kyrgyzstan", capital: "Bishkek" },
  { continent: "Asia", country: "Tajikistan", capital: "Dushanbe" },
  { continent: "Asia", country: "Afghanistan", capital: "Kabul" },
  { continent: "Asia", country: "Pakistan", capital: "Islamabad" },
  { continent: "Asia", country: "India", capital: "New Delhi" },
  { continent: "Asia", country: "Maldives", capital: "Male" },
  { continent: "Asia", country: "Nepal", capital: "Kathmandu" },
  { continent: "Asia", country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
  { continent: "Asia", country: "Bhutan", capital: "Thimphu" },
  { continent: "Asia", country: "Bangladesh", capital: "Dhaka" },
  { continent: "Asia", country: "Mongolia", capital: "Ulaanbaatar" },
  { continent: "Asia", country: "China", capital: "Beijing" },
  { continent: "Asia", country: "Myanmar", capital: "Naypyidaw" },
  { continent: "Asia", country: "Thailand", capital: "Bangkok" },
  { continent: "Asia", country: "Laos", capital: "Vientiane" },
  { continent: "Asia", country: "Cambodia", capital: "Phnom Penh" },
  { continent: "Asia", country: "Vietnam", capital: "Hanoi" },
  { continent: "Asia", country: "Malaysia", capital: "Kuala Lumpur" },
  { continent: "Asia", country: "Singapore", capital: "Singapore" },
  { continent: "Asia", country: "Indonesia", capital: "Jakarta" },
  { continent: "Asia", country: "Brunei", capital: "Bandar Seri Begawan" },
  { continent: "Asia", country: "North Korea", capital: "Pyongyang" },
  { continent: "Asia", country: "South Korea", capital: "Seoul" },
  { continent: "Asia", country: "Taiwan", capital: "Taipei" },
  { continent: "Asia", country: "Philippines", capital: "Manila" },
  { continent: "Asia", country: "Timor-Leste", capital: "Dili" },
  { continent: "Asia", country: "Japan", capital: "Tokyo" },
  { continent: "Australia and Oceania", country: "Palau", capital: "Ngerulmud" },
  { continent: "Australia and Oceania", country: "Federated States of Micronesia", capital: "Palikir" },
  { continent: "Australia and Oceania", country: "Papua New Guinea", capital: "Port Moresby" },
  { continent: "Australia and Oceania", country: "Australia", capital: "Canberra" },
  { continent: "Australia and Oceania", country: "Marshall Islands", capital: "Majuro" },
  { continent: "Australia and Oceania", country: "Nauru", capital: "Yaren" },
  { continent: "Australia and Oceania", country: "Solomon Islands", capital: "Honiara" },
  { continent: "Australia and Oceania", country: "Vanuatu", capital: "Port Vila" },
  { continent: "Australia and Oceania", country: "Tuvalu", capital: "Funafuti" },
  { continent: "Australia and Oceania", country: "Fiji", capital: "Suva" },
  { continent: "Australia and Oceania", country: "New Zealand", capital: "Wellington" },
  { continent: "Australia and Oceania", country: "Samoa", capital: "Apia" },
  { continent: "Australia and Oceania", country: "Tonga", capital: "Nuku'alofa" },
  { continent: "Australia and Oceania", country: "Kiribati", capital: "Tarawa" },
  { continent: "Europe", country: "Iceland", capital: "Reykjavik" },
  { continent: "Europe", country: "Ireland", capital: "Dublin" },
  { continent: "Europe", country: "Portugal", capital: "Lisbon" },
  { continent: "Europe", country: "Spain", capital: "Madrid" },
  { continent: "Europe", country: "United Kingdom", capital: "London" },
  { continent: "Europe", country: "France", capital: "Paris" },
  { continent: "Europe", country: "Andorra", capital: "Andorra la Vella" },
  { continent: "Europe", country: "The Netherlands", capital: "Amsterdam" },
  { continent: "Europe", country: "Belgium", capital: "Brussels" },
  { continent: "Europe", country: "Luxembourg", capital: "Luxembourg|Luxembourg City" },
  { continent: "Europe", country: "Norway", capital: "Oslo" },
  { continent: "Europe", country: "Sweden", capital: "Stockholm" },
  { continent: "Europe", country: "Denmark", capital: "Copenhagen" },
  { continent: "Europe", country: "Germany", capital: "Berlin" },
  { continent: "Europe", country: "Liechtenstein", capital: "Vaduz" },
  { continent: "Europe", country: "Switzerland", capital: "Bern" },
  { continent: "Europe", country: "Italy", capital: "Rome" },
  { continent: "Europe", country: "Monaco", capital: "Monaco" },
  { continent: "Europe", country: "San Marino", capital: "San Marino" },
  { continent: "Europe", country: "Vatican City", capital: "Vatican City" },
  { continent: "Europe", country: "Malta", capital: "Valletta" },
  { continent: "Europe", country: "Czech Republic", capital: "Prague" },
  { continent: "Europe", country: "Austria", capital: "Vienna" },
  { continent: "Europe", country: "Slovenia", capital: "Ljubljana" },
  { continent: "Europe", country: "Poland", capital: "Warsaw" },
  { continent: "Europe", country: "Slovakia", capital: "Bratislava" },
  { continent: "Europe", country: "Hungary", capital: "Budapest" },
  { continent: "Europe", country: "Croatia", capital: "Zagreb" },
  { continent: "Europe", country: "Bosnia and Herzegovina", capital: "Sarajevo" },
  { continent: "Europe", country: "Montenegro", capital: "Podgorica" },
  { continent: "Europe", country: "Serbia", capital: "Belgrade" },
  { continent: "Europe", country: "Kosovo", capital: "Pristina" },
  { continent: "Europe", country: "Albania", capital: "Tirana" },
  { continent: "Europe", country: "North Macedonia", capital: "Skopje" },
  { continent: "Europe", country: "Greece", capital: "Athens" },
  { continent: "Europe", country: "Finland", capital: "Helsinki" },
  { continent: "Europe", country: "Estonia", capital: "Tallinn" },
  { continent: "Europe", country: "Latvia", capital: "Riga" },
  { continent: "Europe", country: "Lithuania", capital: "Vilnius" },
  { continent: "Europe", country: "Belarus", capital: "Minsk" },
  { continent: "Europe", country: "Ukraine", capital: "Kyiv" },
  { continent: "Europe", country: "Moldova", capital: "Chisinau" },
  { continent: "Europe", country: "Romania", capital: "Bucharest" },
  { continent: "Europe", country: "Bulgaria", capital: "Sofia" },
  { continent: "Europe", country: "Russia", capital: "Moscow" },
  { continent: "North America", country: "Canada", capital: "Ottawa" },
  { continent: "North America", country: "United States of America", capital: "Washington D.C." },
  { continent: "North America", country: "Mexico", capital: "Mexico City" },
  { continent: "North America", country: "The Bahamas", capital: "Nassau" },
  { continent: "North America", country: "Cuba", capital: "Havana" },
  { continent: "North America", country: "Jamaica", capital: "Kingston" },
  { continent: "North America", country: "Haiti", capital: "Port-au-Prince" },
  { continent: "North America", country: "Dominican Republic", capital: "Santo Domingo" },
  { continent: "North America", country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { continent: "North America", country: "Antigua and Barbuda", capital: "Saint John's" },
  { continent: "North America", country: "Dominica", capital: "Roseau" },
  { continent: "North America", country: "Saint Lucia", capital: "Castries" },
  { continent: "North America", country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { continent: "North America", country: "Barbados", capital: "Bridgetown" },
  { continent: "North America", country: "Grenada", capital: "Saint George's" },
  { continent: "North America", country: "Trinidad and Tobago", capital: "Port of Spain" },
  { continent: "North America", country: "Belize", capital: "Belmopan" },
  { continent: "North America", country: "Guatemala", capital: "Guatemala City" },
  { continent: "North America", country: "Honduras", capital: "Tegucigalpa" },
  { continent: "North America", country: "El Salvador", capital: "San Salvador" },
  { continent: "North America", country: "Nicaragua", capital: "Managua" },
  { continent: "North America", country: "Costa Rica", capital: "San Jose" },
  { continent: "North America", country: "Panama", capital: "Panama City" },
  { continent: "South America", country: "Colombia", capital: "Bogota" },
  { continent: "South America", country: "Venezuela", capital: "Caracas" },
  { continent: "South America", country: "Guyana", capital: "Georgetown" },
  { continent: "South America", country: "Suriname", capital: "Paramaribo" },
  { continent: "South America", country: "Ecuador", capital: "Quito" },
  { continent: "South America", country: "Peru", capital: "Lima" },
  { continent: "South America", country: "Brazil", capital: "Brasilia" },
  { continent: "South America", country: "Bolivia", capital: "Sucre|La Paz" },
  { continent: "South America", country: "Chile", capital: "Santiago" },
  { continent: "South America", country: "Paraguay", capital: "Asuncion" },
  { continent: "South America", country: "Uruguay", capital: "Montevideo" },
  { continent: "South America", country: "Argentina", capital: "Buenos Aires" }
];

const FM = (window.FastMath = window.FastMath || {});
FM.worldCapitalsData = WORLD_CAPITALS;
export {};
